version: "3.3"
services:
  db:
    container_name: webrise-postgres
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5439:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    build:
      context: ./postgres
      dockerfile: Dockerfile
    hostname: webrise-postgres

volumes:
  postgres:
    driver: local