DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS subscribtions;


CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255),
    email     VARCHAR(255),
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS subscribtions
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sub_name VARCHAR(255),
    user_id  BIGINT references users (id)
);
